name: Github Action CI

on:
  push:
    branches: [ master, gh-actions ]
  pull_request:
    branches: [ master, gh-actions ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install
      run: |
        sudo apt-get update
        sudo apt-get install latexmk libalgorithm-diff-perl texlive texlive-latex-extra texlive-humanities graphviz
        pip3 install --user mako
        pip3 install --user typing
        pip3 install --user Sphinx
        pip3 install --user codespell     
    - name: build pdf
      run: |
        make latexpdf
        mv build/latex/devicetree-specification.pdf build/latex/devicetree-specification-$(git describe).pdf
    - name: build html
      run: make html
    - name: build singlehtml
      run: make singlehtml
    - name: upload
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: |
          build/latex/devicetree-specification-*.pdf
    - name: release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: build/latex/devicetree-specification-*.pdf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
